config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get '/auth/facebook/callback', to: 'sessions#create'
  get '/auth/failure', to: 'session#failure'
  get 'signout', to: 'sessions#destroy'

  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :cities
    resources :users, only: [:index, :destroy, :update]
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, presence: true, uniqueness: true
  validates :provider, :name, :oauth_token, :oauth_expires_at, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.image = auth.info.image
      user.save!
    end
  end

  private

  def user_params
    params.permit(:provider, :uid, :name, :oauth_token, :oauth_expires_at)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:update, :destroy]

  def index
    @users = User.all
  end

  def destroy
    @user.destroy

    flash.alert = 'User was successfully destroyed.'
    redirect_to admin_users_url
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'User was updated!'
      render json: { :message => 'User updated successfully' }
    else
      flash[:error] = 'Oops! Something went wrong.'
      render json: { :errors => @user.errors.full_messages }, :status => :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:admin)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  after_action :flash_to_headers

  def flash_to_headers
    return unless request.xhr?

    response.headers['X-Message'] = flash_messages

    flash.discard
  end

  private

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def flash_messages
    [:success, :error, :alert, :notice].
      reject { |type| flash[type].blank? }.
      map { |type| "#{type}:#{flash[type]}" }.
      join(',')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    # flash.now[:notice] = 'home!'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(auth_hash)
    session[:user_id] = user.id
    redirect_to root_url
  end

  def failure
    flash.alert = 'Failed to authenticate'
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice('alert', 'error', 'notice', 'success')
  end
end

app/views/admin/index.html.erb
<h1>Admin</h1>
<ul>
  <li><%= link_to('Users', admin_users_path) %></li>
</ul>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Provider</th>
    <th>Admin?</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.image %></td>
        <td><%= user.name %></td>
        <td><%= user.provider %></td>
          <%= form_for([:admin, user], method: :put, remote: true) do |f| %>
            <td>
              <%= f.check_box :admin  %>
            </td>
            <td>
              <%= f.submit 'save' %>
            </td>
          <% end %>
          <td><%= link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<div id="flashes" class="flashes">
  <% user_facing_flashes.each do |key, value| -%>
    <div class="flash-<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_nav.erb
<section class="navbar">
  <%= fa_icon 'bars 2x', class: 'js-menu-trigger sliding-panel-button' %>

  <nav class="js-menu sliding-panel-content">
    <ul>
      <li><%= link_to 'Home', root_path%></li>
      <li><%= link_to 'Admin', admin_path%></li>
    </ul>
  </nav>

  <div class="js-menu-screen sliding-panel-fade-screen"></div>

  <div class="user-widget">
    <% if current_user %>
        <%= image_tag current_user.image, class: 'fb-picture' %>
        <%= button_to 'Sign out', signout_path, id: 'sign_out', :method => 'get', :form_class => 'sign_in_out_form' %>
    <% else %>
        <%= button_to 'Sign in', '/auth/facebook', id: 'sign_in', :method => 'get', :form_class => 'sign_in_out_form' %>
    <% end %>
  </div>
</section>

app/views/home/show.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'flashes' -%>
  <%= render 'nav' %>

  <section>
    <%= yield %>
  </section>

  <%= render 'javascript' %>
  <%= render 'css_overrides' %>
</body>
</html>